---
name: "cache-go - restore"

inputs:
  s3_credentials:
    description: |
      The S3 credentials as a JSON object. Must contain the following keys:

      - endpoint (no URL scheme)
      - access_key
      - secret_key
      - bucket_name
    type: "string"
    required: true
  name:
    type: "string"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Retrieve go configuration"
      uses: "bckground/actions/cache-go/internal@main"
      id: "go-config"

    - name: "Clean cache directories"
      shell: "bash"
      run: |
        go clean -cache -modcache

    - name: "Restore go caches"
      uses: "bckground/actions-cache/restore@9c316ce988fd9d40977dad01d0c7fa06792fa0da"
      with:
        endpoint: "${{ fromJson(inputs.s3_credentials).endpoint }}"
        accessKey: "${{ fromJson(inputs.s3_credentials).access_key }}"
        secretKey: "${{ fromJson(inputs.s3_credentials).secret_key }}"
        bucket: "${{ fromJson(inputs.s3_credentials).bucket_name }}"
        use-fallback: false
        key: "go-${{ steps.go-config.outputs.go_version }}-${{ inputs.name }}-at-${{ github.repository }}-on-${{ runner.os }}-${{ runner.arch }}-"
        restore-keys: |
          go-${{ steps.go-config.outputs.go_version }}-${{ inputs.name }}-at-${{ github.repository }}-on-${{ runner.os }}-${{ runner.arch }}-
        path: |
          ${{ steps.go-config.outputs.mod_cache }}
          ${{ steps.go-config.outputs.build_cache }}
