version: 2
# NOTE:
#
# schedule.interval does NOT apply to security updates. dependabot creates PRs
# for security updates ASAP.
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: ["area/dependencies"]
