---
name: "setup-mise - save"

inputs:
  s3_credentials:
    description: |
      The S3 credentials as a JSON object. Must contain the following keys:

      - endpoint (no URL scheme)
      - access_key
      - secret_key
      - bucket_name
    type: "string"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Retrieve mise configuration"
      uses: "bckground/actions/setup-mise/internal@main"
      id: "mise-config"

    - name: "Cache mise"
      uses: bckground/actions-cache/save@8a7e86207dc72a3f6bd8cbc23f4f061558fee8f8
      with:
        endpoint: ${{ fromJson(inputs.s3_credentials).endpoint }}
        accessKey: ${{ fromJson(inputs.s3_credentials).access_key }}
        secretKey: ${{ fromJson(inputs.s3_credentials).secret_key }}
        bucket: ${{ fromJson(inputs.s3_credentials).bucket_name }}
        use-fallback: false
        key: "mise-at-${{ github.repository }}-on-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}"
        path: |
          ${{ steps.mise-config.outputs.data_dir }}
