---
name: "save mise setup"

inputs:
  cache_s3_endpoint:
    type: "string"
    required: true
  cache_s3_access_key:
    type: "string"
    required: true
  cache_s3_secret_key:
    type: "string"
    required: true
  cache_s3_bucket_name:
    type: "string"
    required: true

outputs:
  data-dir:
    description: "The path to mise's data directory"
    value: "${{ steps.mise-cache-dirs.outputs.data_dir }}"

runs:
  using: "composite"
  steps:
    - name: "Retrieve mise directories to cache"
      uses: "bckground/actions/setup-mise/internal@main"
      id: "mise-cache-dirs"

    - name: "Save mise directories"
      uses: bckground/actions-cache/save@8a7e86207dc72a3f6bd8cbc23f4f061558fee8f8
      with:
        endpoint: "${{ inputs.cache_s3_endpoint }}"
        accessKey: "${{ inputs.cache_s3_access_key }}"
        secretKey: "${{ inputs.cache_s3_secret_key }}"
        bucket: "${{ inputs.cache_s3_bucket_name }}"
        use-fallback: false
        key: mise-on-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
        path: |
          ${{ steps.mise-cache-dirs.outputs.data_dir }}
