---
name: "mise - internal"

outputs:
  data-dir:
    description: "The path to mise's data directory"
    value: "${{ steps.mise-cache-dirs.outputs.data-dir }}"

runs:
  using: "composite"
  steps:
    - name: "Retrieve mise directories to cache"
      id: "mise-cache-dirs"
      shell: "bash"
      run: |
        echo "data-dir=${MISE_DATA_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/mise}" | tee -a "$GITHUB_OUTPUT"
