---
name: "cache-go - internal"

outputs:
  go_version:
    description: "The go version installed"
    value: ${{ steps.go-config.outputs.go_version  }}
  mod_cache:
    description: "The path to the go module cache"
    value: ${{ steps.go-config.outputs.mod_cache }}
  build_cache:
    description: "The path to the go build cache"
    value: ${{ steps.go-config.outputs.build_cache }}

runs:
  using: "composite"
  steps:
    - name: "Retrieve go configuration"
      id: "go-config"
      shell: "bash"
      run: |
        echo "go_version=$(go env GOVERSION | sed 's/^go//')" | tee -a "$GITHUB_OUTPUT"
        echo "mod_cache=$(go env GOMODCACHE)" | tee -a "$GITHUB_OUTPUT"
        echo "build_cache=$(go env GOCACHE)" | tee -a "$GITHUB_OUTPUT"
