---
name: "cache-go - internal"

inputs:
  name:
    type: "string"
    required: true
  dependency-path:
    type: "string"
    required: true

outputs:
  go_version:
    description: "The go version installed"
    value: ${{ steps.go-config.outputs.go_version  }}
  mod_cache:
    description: "The path to the go module cache"
    value: ${{ steps.go-config.outputs.mod_cache }}
  build_cache:
    description: "The path to the go build cache"
    value: ${{ steps.go-config.outputs.build_cache }}
  cache_key:
    description: "The full cache key"
    value: ${{ steps.cache-keys.outputs.key }}
  cache_restore_key:
    description: "The cache restore key prefix"
    value: ${{ steps.cache-keys.outputs.restore-key }}

runs:
  using: "composite"
  steps:
    - name: "Retrieve go configuration"
      id: "go-config"
      shell: "bash"
      run: |
        echo "go_version=$(go env GOVERSION | sed 's/^go//')" | tee -a "$GITHUB_OUTPUT"
        echo "mod_cache=$(go env GOMODCACHE)" | tee -a "$GITHUB_OUTPUT"
        echo "build_cache=$(go env GOCACHE)" | tee -a "$GITHUB_OUTPUT"

    - name: "Calculate dependency hash"
      id: "dependency-hash"
      uses: "actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd" # v8.0.0
      env:
        DEPENDENCY_PATH: "${{ inputs.dependency-path }}"
      with:
        script: |
          const fs = require('fs');
          const crypto = require('crypto');
          const glob = require('@actions/glob');

          const patterns = process.env.DEPENDENCY_PATH;
          const globber = await glob.create(patterns);
          const files = (await globber.glob()).sort();

          console.log('Files being hashed:', files);

          const hash = crypto.createHash('sha256');
          for (const file of files) {
            if (fs.existsSync(file)) {
              console.log('Hashing file:', file);
              const content = fs.readFileSync(file);
              hash.update(content);
            } else {
              console.log('File not found:', file);
            }
          }

          core.setOutput('hash', hash.digest('hex'));

    - name: "Generate cache keys"
      id: "cache-keys"
      shell: "bash"
      run: |
        repo="${{ github.repository }}"
        prefix="go-${{ steps.go-config.outputs.go_version }}-${{ inputs.name }}-at-${repo//\//-}-on-${{ runner.os }}-${{ runner.arch }}"
        echo "key=${prefix}-${{ steps.dependency-hash.outputs.hash }}" | tee -a "$GITHUB_OUTPUT"
        echo "restore-key=${prefix}-" | tee -a "$GITHUB_OUTPUT"
