---
# For security reasons, the workflow in which the autofix.ci action is used must be named "autofix.ci".
name: "autofix.ci"

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  prettier:
    name: "prettier"
    runs-on: "blacksmith-2vcpu-ubuntu-2404-arm"
    env:
      S3_CREDENTIALS: >-
        ${{ format('{{"endpoint": "{0}", "access_key": "{1}", "secret_key": "{2}", "bucket_name": "{3}"}}',
        secrets.OVH_GHA_CACHE_ENDPOINT, vars.OVH_GHA_CACHE_USER_SECRET_ID, secrets.OVH_GHA_CACHE_USER_SECRET, secrets.OVH_GHA_CACHE_BUCKET_NAME) }}
    steps:
      - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0

      - uses: "bckground/actions/setup-mise@main"
        with:
          cache-backend: "github"
          s3-credentials: "${{ env.S3_CREDENTIALS }}"

      - name: "Run prettier"
        run: |
          prettier --config .prettierrc.yml --write "**/*.{yml,yaml,md,markdown,json,jsonc}"

      - name: "Run autofix"
        uses: "autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a"
