---
name: "CLA"

on:
  issue_comment:
    types:
      - "created"
  pull_request_target:
    types:
      - "opened"
      - "closed"
      - "synchronize"

jobs:
  check_cla_signature:
    name: "check signature"
    runs-on: "ubuntu-latest"
    permissions:
      actions: "write"
      contents: "read" # CLA signatures are stored in https://github.com/bckground/cla
      pull-requests: "write"
      statuses: "write"
    steps:
      - uses: "bckground/actions/cla-check@main"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          cla_assistant_token: "${{ secrets.CLA_ASSISTANT_ACCESS_TOKEN }}"
