---
name: "lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: ["*"]

jobs:
  prettier:
    name: "prettier"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"

      - uses: "bckground/actions/setup-mise/restore@main"
        with:
          cache-s3-endpoint: ${{ secrets.OVH_GHA_CACHE_ENDPOINT }}
          cache-s3-access-key: ${{ vars.OVH_GHA_CACHE_USER_SECRET_ID }}
          cache-s3-secret-key: ${{ secrets.OVH_GHA_CACHE_USER_SECRET }}
          cache-s3-bucket-name: ${{ secrets.OVH_GHA_CACHE_BUCKET_NAME }}

      - uses: "bckground/actions/autofix-prettier@main"

      - if: github.ref_name == 'main'
        uses: bckground/actions/setup-mise/save@main
